# User config
author: "Annemarie Dapoz"
tagline: "Engineering Portfolio"
description: "Welcome! My name is Annemarie, and I am a mechanical and ocean engineer with a focus in mechanism design, prototyping, and testing."
email: "adapoz@mit.edu"
linkedin: "https://www.linkedin.com/in/annemarie-dapoz/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: "/adapoz"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
