# User config
author: "Temp Name"
tagline: "Engineering Portfolio"
description: "Welcome! I'm xxxxx, a mechanical and ocean engineer with a focus on machine and mechanism design."
email: "pineapple@example.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: "/portfolio"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
