# User config
author: "Annemarie Dapoz"
tagline: "Engineering Portfolio"
description: "Welcome! I'm Annemarie, a mechanical and ocean engineer with a focus on machine and mechanism design."
email: "adapoz@mit.edu"
linkedin: "https://www.linkedin.com/annemarie-dapoz"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: "/portfolio"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
